package:
  name: iventure
  version: {{ CONDA_PACKAGE_VERSION }}

source:
  path: ../

build:
  script: python setup.py install

requirements:
  build:
    - git
    - python 2.7.*
  run:
    # add bayeslite>0.2.0rc1 when it's packaged
    - matplotlib >=1.4,<2.1
    - numpy 1.8.*
    - pandas >=0.14,<0.19
    - scipy >=0.13,<=0.19.*

test:
  requires:
    - pytest 2.5.1.*
    - python 2.7.*
  commands:
    - python -m pytest --pyargs iventure -k "not __ci_"

about:
  home: https://github.com/probcomp/iventure
