package:
  name: iventure
  version: "0.1"

source:
  path: ../

build:
  script: python setup.py install

requirements:
  build:
    - git
    - python 2.7.*
  run:
    # add bayeslite>0.2.0rc1 when it's packaged
    - matplotlib
    - numpy
    - pandas
    - scipy

test:
  requires:
    - python 2.7.*
    - pytest 2.5.1.*
  commands:
    - python -m pytest --pyargs iventure -k "not __ci_"

about:
  home: https://github.com/probcomp/iventure
